name: Reviewdog - EditorConfig

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  editorconfig:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: eclint
        uses: reviewdog/action-eclint@v1
        with:
          github_token: ${{ secrets.CRUFT_GITHUB_ACCESS_TOKEN }}
          reporter: github-pr-review # Change reporter.
          eclint_flags: './'
